// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misc.Song.ShareClub.DataAccess;

namespace Misc.Song.ShareClub.DataAccess.Migrations
{
    [DbContext(typeof(ShareContext))]
    [Migration("20200506084857_addInfo")]
    partial class addInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Misc.Song.ShareClub.Models.FileInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FTypeid")
                        .HasColumnType("int");

                    b.Property<int>("PageView")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<int>("downloadCount")
                        .HasColumnType("int");

                    b.Property<string>("fileName")
                        .HasColumnType("text");

                    b.Property<int>("fileSize")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("FTypeid");

                    b.HasIndex("Userid");

                    b.ToTable("fileInfos");
                });

            modelBuilder.Entity("Misc.Song.ShareClub.Models.FileType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("typeName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("fileTypes");
                });

            modelBuilder.Entity("Misc.Song.ShareClub.Models.UserInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.Property<string>("userPwd")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userInfos");
                });

            modelBuilder.Entity("Misc.Song.ShareClub.Models.UserLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ipAddress")
                        .HasColumnType("text");

                    b.Property<string>("latitude")
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userLogs");
                });

            modelBuilder.Entity("Misc.Song.ShareClub.Models.FileInfo", b =>
                {
                    b.HasOne("Misc.Song.ShareClub.Models.FileType", "FType")
                        .WithMany()
                        .HasForeignKey("FTypeid");

                    b.HasOne("Misc.Song.ShareClub.Models.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("Userid");
                });
#pragma warning restore 612, 618
        }
    }
}
